GET http://localhost:3001/diets
Content-Type: application/json


#######



POST http://localhost:3001/recipes
Content-Type: application/json

{
    "name": "Jotencietoss",
    "image": "thattheimage",
    "summary": "summary",
    "healthScore": 2,
    "steps": "asdjkasdljklklasd",
    "diets": [
        "gluten free",
        "dairy free",
        "lacto ovo vegetarian",
        "vegan"
    ]
}
